name: Multi-environment matrix with approvals

on: push

jobs:
  detect-environments:
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.environments.outputs.result }}
    steps:
      - uses: actions/github-script@v6
        id: environments
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: json
          script: |
            const {data: {environments}} = await github.request(`GET /repos/${process.env.GITHUB_REPOSITORY}/environments`, {
              owner: process.env.GITHUB_REPOSITORY_OWNER,
              repo: context.payload
            });
            return environments.map(e => e.name)
  deploy:
    runs-on: ubuntu-latest
    needs: [detect-environments]
    strategy:
      matrix:
        environment: ${{ fromJSON(needs.detect-environments.outputs.environments) }}
    environment: ${{ matrix.environment }}
    steps:
      - run: echo "Deploying to environment ${{ matrix.environment }}"

